# Generated by Django 4.2.5 on 2023-09-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_username', models.CharField(max_length=100)),
                ('leader_username', models.CharField(max_length=100)),
            ],
        ),
    ]
