# Generated by Django 4.2.5 on 2023-10-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_like_post', to='core.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id_post', to='core.profile'),
            preserve_default=False,
        ),
    ]
