# Generated by Django 5.0.1 on 2024-02-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('psgc_code', models.CharField(max_length=255, unique=True)),
                ('city_municipality_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('province_code', models.CharField(max_length=255, unique=True)),
                ('psgc_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('psgc_code', models.CharField(max_length=255, unique=True)),
                ('region_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('barangay_code', models.CharField(max_length=255, unique=True)),
                ('city_municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.city_municipality')),
            ],
        ),
        migrations.AddField(
            model_name='city_municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.region'),
        ),
    ]
